### ISSUE TITLE
Please add a release version

### ISSUE THREAD

**Issue by XerxesDGreat** [sensiolabs/consul-php-sdk#10]
We like this library, but in order to use it in our production environment, we need to specify an explicit version in order to protect against unexpected upgrades. Can you create a solid release version? Thanks!

**Comment by lyrixx** [comment]
Here we go https://github.com/sensiolabs/consul-php-sdk/releases/tag/v1.0.0 ;)

**Comment by XerxesDGreat** [comment]
Thank you!
