### ISSUE TITLE
Bump up version of guzzle

### ISSUE THREAD

**Issue by smarijic** [sensiolabs/consul-php-sdk#16]
Hi,
I need aws sdk and consul sdk, but the problem is that I can not install both of them due to collision with guzzle versions. I get following message from composer.

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: remove guzzlehttp/guzzle 6.1.1
>     - Conclusion: don't install guzzlehttp/guzzle 5.3.0
>     - Installation request for sensiolabs/consul-php-sdk ^1.0 -> satisfiable by sensiolabs/consul-php-sdk[v1.0.0].
>     - Conclusion: don't install guzzlehttp/guzzle 6.1.1
>     - sensiolabs/consul-php-sdk v1.0.0 requires guzzlehttp/guzzle >=4,<6 -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0].
>     - Can only install one of: guzzlehttp/guzzle[4.0.0, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.0.1, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.0.2, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.1.0, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.1.1, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.1.2, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.1.3, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.1.4, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.1.5, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.1.6, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.1.7, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.1.8, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.2.0, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.2.1, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.2.2, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[4.2.3, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[5.0.0, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[5.0.1, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[5.0.2, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[5.0.3, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.1.1].
>     - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.1.1].
>     - Installation request for guzzlehttp/guzzle == 6.1.1.0 -> satisfiable by guzzlehttp/guzzle[6.1.1].

Can you bump up version of guzzle to 6.1 or 6.1.1?

**Comment by lyrixx** [comment]
Hello.

I just released v2.0.0
