### ISSUE TITLE
Connection details

### ISSUE THREAD

**Issue by mariusmitrofan** [sensiolabs/consul-php-sdk#29]
I'm trying to use your SDK to connect to consul, but I can't find anyway to set up the connection details to my consul server.

Can you shed some light on this?

**Comment by mariusmitrofan** [comment]
Hm. I think I found the answer here -> https://github.com/sensiolabs/consul-php-sdk/pull/28/files

**Comment by lyrixx** [comment]
Yes, indeed. And I just merged the PR ;)
