### ISSUE TITLE
Is the the right place to add a simple Symfony2 Bundle?

### ISSUE THREAD

**Issue by lyrixx** [sensiolabs/consul-php-sdk#8]
Why do we need the bundle?

* Because we want to configure once my consul configuration
* Because we want to re-use "consul service". So the bundle could expose few "symfony service".

**Comment by hacfi** [comment]
I like the idea. Personally I think the way yohang does it in finite https://github.com/yohang/Finite/tree/master/src/Finite is very nice. With so little files at the moment I think it doesn’t blow up this library.

**Comment by lyrixx** [comment]
Actually, we did not need a bundle.
So I'm closing the issue.

**Comment by lyrixx** [comment]
And anyway, the answer is yes.
